#!/bin/bash

conan create --version 1.6.1-dev --build=missing up-core-api/developer && \
conan create --version 1.1.0-dev --build=missing up-cpp/developer && \
conan create --version 1.0.0-rc4 --build=missing zenohc-tmp/prebuilt && \
conan create --version 1.0.0-rc4 --build=missing zenohcpp-tmp/from-source
